### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by thomasgcompany** [MishUshakov/dialogflow-web#22]
Hi Mish,

I've tried to change the language to nl but it does not work.
How can i change the language?

Regards,

Thomas

**Comment by kimneu** [comment]
Hi @thomasgcompany 

you can change the language in the `config.js`-file in line 17 and 18:

`        settings: {
            speechLang: "en-GB", // <- output language
            recognitionLang: "en-US" // <- input(recognition) language
`

you find the supported languages here: [https://dialogflow.com/docs/reference/language](url)

and of course you need to change the language of your dialogflow agent.
You find that in the settings: [https://dialogflow.com/docs/agents#settings](url)

Happy chatting

Kim

**Comment by thomasgcompany** [comment]
Hi,

I've recorded a screencast with speechLang on: 'nl' and recognitionLang also on 'nl'.
https://drive.google.com/file/d/1F7Jr5WxGEf47MD62HpgrxdmyXVZDSK_Q/view

Regards,

Thomas

**Comment by MishUshakov** [comment]
@thomasgcompany do you have built the webapp after the changes in `config.js`? Should work fine :)

**Comment by MishUshakov** [comment]
@thomasgcompany try setting your `recognitionLang` to `nl-NL` should work!

**Comment by thomasgcompany** [comment]
@MishUshakov Sorry did not work, any ideas?

**Comment by MishUshakov** [comment]
@thomasgcompany ok, was actually my fault, notice `recognition.lang = config.locale.strings.recognitionLang` on the line 220. Actually it is `config.locale.settings.recognitionLang` so, that's the reason it didn't worked ;)

**Comment by MishUshakov** [comment]
@thomasgcompany upgrade to 8103f5593f1ad12a383b298a033a31d822506767
And please report :)
