### ISSUE TITLE
Problem running locally

### ISSUE THREAD

**Issue by magendhiran** [MishUshakov/dialogflow-web#35]
Hi, Thanks for the web ui code, i'm trying to run this code in local using npm , but when the dev launch in localhost it always connect with your bot even when i changed token in config.js , what am i missing, i did following steps 

git clone <<git url>>
npm install 
npm run build
npm run dev

local code done not have any token reference your bot when when it runs it alwas take your bot token why ?

**Comment by magendhiran** [comment]
when i run npm run dev its always building with your bot token , not taking my token .

**Comment by MishUshakov** [comment]
@magendhiran Hey, thank you for using my library! Please make sure, that you have changed your token in `config.js`
Also make sure, to clear your browser cache, localstoarage, etc. because web worker caches everything automagically

**Comment by magendhiran** [comment]
thank you ! its my browser cached files , fixed after clearing
