### ISSUE TITLE
Microphone is not working

### ISSUE THREAD

**Issue by balavenkatesh3322** [MishUshakov/dialogflow-web#36]
User request as voice messeage is not working.respone sendind as goahead i'm listing it's not taking user voice.

Your website https://mish.io/dialogflow-web microphone is not working

Thanks

**Comment by MishUshakov** [comment]
@balavenkatesh3322 hey, could you specify more information about your environment? Which browser and operating system do you use? Have you allowed microphone access in your browser?

**Comment by balavenkatesh3322** [comment]
Hi @MishUshakov, I check Chrome and Firefox browser both are not working,operating system Ubuntu and windows both are not working, I allowed microphone as well.

Have attached screenshot for your refernce
![screenshot from 2018-05-26 16-13-53](https://user-images.githubusercontent.com/24771457/40575284-e34d258c-60ff-11e8-9cc5-61071b1c0c22.png)

Thanks @MishUshakov

**Comment by MishUshakov** [comment]
@balavenkatesh3322 ok, I will check on that and notify you here!

**Comment by balavenkatesh3322** [comment]
But chrome browser is still not working in windows os and ubuntu os. Is there any reason for that?
Did you try chrome browser in windows or ubuntu?

**Comment by balavenkatesh3322** [comment]
Hi @MishUshakov Is there any way to fix the microphone issue. Please let me know if you find it.

Thanks

**Comment by MishUshakov** [comment]
@balavenkatesh3322 hey, I tried on Windows 10 + Chrome, Firefox, Edge and it worked pretty well, I also tried on Android with Samsung Browser and Chrome. When I tried on Mac OS and Chrome it didn't worked. So try using different microphone maybe? I will look on API docs, maybe im doing something wrong, but I will keep you updated on this topic! 👍

**Comment by balavenkatesh3322** [comment]
@MishUshakov Please update this issue. Still this is not fixed.

**Comment by MishUshakov** [comment]
@balavenkatesh3322 hey! I'm trying to find the root of the problem here. But I never saw any proper reports/logs/etc. it does not help me further to find the bug(if there is one at all)
