### ISSUE TITLE
Webhook fulfillment with v2

### ISSUE THREAD

**Issue by harshadabhanose** [MishUshakov/dialogflow-web#55]
Can I use this project if I am using DialogFlow API v2 with Google Functions as fulfillment? If yes, then can you please let me know what all changes I need to do? I really found this WebUI awesome and want to use it for my bot built with DialogFlow. Thanks.

**Comment by Primtek** [comment]
same here :) .. waiting for API v2.. API v2 will be deprecated soon

**Comment by MishUshakov** [comment]
Let's clarify the situation here. The dialogflow-web frontend is using `api-ai-javascript` library to make requests to dialogflow API. The library is using V1 API and at the moment has no support for V2 you guys are asking for. If @google will update the library to support the V2 API or someone from GitHub will make own implementation, I will update the WebUI Immediately. It's not my task to make a client for someone's APIs, I'm just making frontend work here and not interested in the whole OAuth/Token crutches

**Comment by MishUshakov** [comment]
Im closing this, see #65
