### ISSUE TITLE
how to listen to ethernet ip?

### ISSUE THREAD

**Issue by Primtek** [MishUshakov/dialogflow-web#56]
Hi..

this project looks awesome :)
how to change the listener IP to 172.16.1.88 .. so it accessible on LAN 

[root@ai df-widget]# npm run dev

> dialogflow-widget@1.6.6 dev /home/df-widget
> cross-env NODE_ENV=development webpack-dev-server --open --hot

Project is running at http://localhost:8080/
webpack output is served from /dist/
404s will fallback to /index.html

**Comment by MishUshakov** [comment]
1. Build it
2. `python -m SimpleHTTPServer 80`
3. Or change the dev script in package.json to `cross-env NODE_ENV=development webpack-dev-server --open --hot --host 0.0.0.0`

**Comment by Primtek** [comment]
Hi. 

I tried to add

 --host 0.0.0.0

to package.json

The browser shows Invalid response header

Thanks & Regards

Winanjaya
+62 817 145779

================
Sent from my iPhone
================
