### ISSUE TITLE
Support for Knowledge connectors?

### ISSUE THREAD

**Issue by Jorisdieben** [MishUshakov/dialogflow-web#62]
Hi, I really like your code. And I am thinking of using it in production. I am using the V2 API and Beta features and most of that seems to work as well in your frontend. Although you clearly indicate that V2 isn't supported. Can you specify what is supported and what not? And would you suggest using your code going forward on production?

I am using the knowledge connector for example and that seems to work fine when I test it within Dialogflow but doesn't return any results (except for the fallback intent) in your frontend. Do you know why?

**Comment by MishUshakov** [comment]
Hey, @Jorisdieben
I don't really know what knowledge connector is, looks like it's time to refresh my skill here. Yeah, V2 is not currently supported, see #55. You can use this client as basis for your production application. In the end of the day this app is just a good showcase, how you can utilise Dialogflow API, so if it's not critical consider building your own (it's a lot of fun!).

I have to test it out for myself, to see what I can do here, to make it more stable and updated. But you can submit pull requests, if you have some progress going on here.

Best regards.

**Comment by Jorisdieben** [comment]
Hi @MishUshakov 
Thanks for your reply. It was not really clear for me what the differences are from API1 vs API2 and how that relates to your frontend. I see now that for authentication I need to build a backend and let that work with your frontend. This repo https://github.com/rkmighwal/Dialogflow-V2-UI used your design to connect the frontend and to the backend. Would be nice if Google improved their documentation and SDKs to help out with setting up a Web UI. If I have some progress I will let you know. Thanks again.
