### ISSUE TITLE
It does not work on internet explorer 11

### ISSUE THREAD

**Issue by jaime070791** [MishUshakov/dialogflow-web#63]
Hello, congratulations for your application, we appreciate the effort you have made in building it.
However, when it is opened in the Internet Explorer 11 browser, it does not work. It does not load the contents of the bot and the blank screen remains
Thank you!

**Comment by MishUshakov** [comment]
Hey, try changing babel and web pack config. It works on IE8+
Also don't forget to enable JavaScript in your browser settings
