### ISSUE TITLE
Example DialogFlow quick replies

### ISSUE THREAD

**Issue by Vadorequest** [MishUshakov/dialogflow-web#66]
How can we configure this web application to display quick replies? Since there is no way of doing so through DialogFlow Console.

I setup a very simple bot with a few quick replies for Facebook integration, used the bot "client key" using the https://github.com/MishUshakov/dialogflow-widget project but the Facebook quick replies didn't show up on the web app. (it's probably normal, but I don't yet understand how we're supposed to tell DialogFlow to use quick replies in the "default" integration. Did I miss something? Is there an example somewhere?

Thanks.

**Comment by MishUshakov** [comment]
Inspect dialogflow dashboard, my implementation works

**Comment by Vadorequest** [comment]
Do you have any tutorial or guide? I don't doubt your implementation works, just don't understand how it does.

Since there is no option on Dialogflow dashboard to configure the web integration, how do you configure it so it display a simple "quick reply"?

**Comment by MishUshakov** [comment]
@Vadorequest you can press on "+" and add Google Assistant "Simple response" like on screenshoot

<img width="940" alt="screenshot 2018-11-05 at 13 30 44" src="https://user-images.githubusercontent.com/10400064/47992839-00d45d80-e0ff-11e8-8d42-1daf51e7b0f7.png">
