### ISSUE TITLE
how to deploy this project on google cloud?

### ISSUE THREAD

**Issue by dhavalp** [MishUshakov/dialogflow-web#67]
i tried to run this project on on different port and IP. I tried to run it using "npm run dev --port 8090" this command i am getting error.
![error_chat](https://user-images.githubusercontent.com/8337429/49292761-25d8a800-f4d4-11e8-9567-e3e3767bfe34.png)

**Comment by MishUshakov** [comment]
Hey @dhavalp, you don't run it on a webpack dev-server for production uses. You build it and serve it on a static Web Server (apache, nginx or firebase)

try
`npm run build`
and move the directory to your "public" folder
