### ISSUE TITLE
How to look at my agent in development mode.

### ISSUE THREAD

**Issue by ktt9117** [MishUshakov/dialogflow-web#68]
I changed the token in config.js to my agent's access key.
And when I put the "npm run build" on a static web server, the agent of the dialogflow I created responds. 

However, "npm run dev" always responds to your agent. 
How do I get my agent to look at the "npm run dev"? 

I've emptied my browser's cache and tried to refresh it, but it does not work.

**Comment by MishUshakov** [comment]
If you use Chrome
Press on 3 dots at the top right corner
Go to More Tools > Developer Tools
In the developer Tools open "Application" tab
Go to "Clear storage", then press on "Clear site Data"

For Safari activate the developer tools and press "Develop" > "Empty Caches"
