### ISSUE TITLE
Error cross-env NODE_ENV=production webpack

### ISSUE THREAD

**Issue by SmartParks** [MishUshakov/dialogflow-web#9]
Several of us are getting this error when running "npm run build".

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dialogflow-web@1.6.6 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dialogflow-web@1.6.6 build script.

**Comment by MishUshakov** [comment]
I will check on that :)

**Comment by MishUshakov** [comment]
@SmartParks which version of Node.JS, npm and Operating System do you use?

**Comment by MishUshakov** [comment]
Didn't heard anything from you, im going to close the issue, if you have more info, just comment here

**Comment by SmartParks** [comment]
This problem was occurring for 6 of us on Macs.  We resolved the problem by using "npm install" instead of "npm init".  You'll want to update this first step in the install instructions.

**Comment by MishUshakov** [comment]
@SmartParks ok, thank you! Will fix it!

**Comment by MishUshakov** [comment]
@SmartParks Don't worry! I have a small roadmap and the update will come with new Material Design update and V2 library! It won't take much time!

**Comment by SmartParks** [comment]
Please change from npm init to npm install.

**Comment by MishUshakov** [comment]
@SmartParks I just dropped out of school, expect update soon, this weekend - I promise
